import "~/styles/globals.css";
import Header from "~/components/Header";
import { Toaster } from "~/components/ui/toaster";

import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={``}>
      <body>
        <Header />
        {children} <Toaster />
      </body>
    </html>
  );
}
